#!/usr/bin/env python3
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any


def default_debug_log_path() -> Path:
    return Path(__file__).resolve().parents[3] / "DEBUG_LOG.md"


def _make_json_safe(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(key): _make_json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_make_json_safe(item) for item in value]
    return value


def ensure_debug_log(log_path: Path) -> Path:
    resolved = log_path.resolve()
    resolved.parent.mkdir(parents=True, exist_ok=True)
    if not resolved.exists():
        resolved.write_text(
            "# Signal to Obsidian Debug Log\n\n"
            "Append-only runtime publish/debug log generated by `deploy/n8n/scripts/*`.\n",
            encoding="utf-8",
        )
    return resolved


def append_debug_log(
    *,
    script_name: str,
    stage: str,
    status: str,
    summary: str,
    details: dict[str, Any] | None = None,
    raw_output: str | None = None,
    log_path: Path | None = None,
) -> Path:
    resolved = ensure_debug_log(log_path or default_debug_log_path())
    timestamp = datetime.now().astimezone().isoformat(timespec="seconds")
    with resolved.open("a", encoding="utf-8") as handle:
        handle.write(f"\n## {timestamp} | {stage} | {status}\n")
        handle.write(f"- script: `{script_name}`\n")
        handle.write(f"- summary: {summary}\n")
        if details is not None:
            handle.write("```json\n")
            handle.write(
                json.dumps(
                    _make_json_safe(details),
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                    default=str,
                )
            )
            handle.write("\n```\n")
        if raw_output:
            text = raw_output.strip()
            if text:
                handle.write("```text\n")
                handle.write(text.replace("\x00", "\\0"))
                handle.write("\n```\n")
    return resolved
